
name: CI + CD Pipline

#Defining when a workflow should run
on:
  push:
    branches: [ main ]
  pull_request: :
    branches: [ main ]
  workflow_dispatch:


#Defining jobs that should run
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: echo Code is being compiled at this stage

#Deployment to Development environment job
  DeplyDev:
    name: Deploy to Development
    if: github.event_name == 'pull_request'
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev.website.com'
    steps:
      - name: Deploy
        run: echo Code is being Deployed at this stage towards http://dev.testing.com

# Deployment to staging environment job
  DeployStaging:
    name: Deploy to staging environment
    if: github.event.ref == 'refs/heads/main'
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.website.com'
    steps:
      - name: Deploy
        run: echo Code is being Deployed at this stage towards staging at http://test.website.com

#Deployment to production job
  DeployProduction:
    name: Deploy to production
    needs: [ DeployStaging ]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.website.com'
    steps:
      - name: Deploy
        run: echo Code is being Deployed at this stage towards Production at http://www.website.com